# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk14

services:
  - postgresql
before_install:
  - psql -c 'create database tracker;' -U postgres
ceche:
  directories:
    - $HOME/.m2
# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)
# Отправлять уведомление на почту gipsyscrew@gmail.com если сборка упала
notifications:
  email:
    recipients:
      - gipsyscrew@gmail.com
    on_success: never # default: change
    on_failure: always # default: always
env:
  global:
    - CODECOV_TOKEN="e0466261-153b-4523-8b20-57e0062bf103"
